import { jsPDF } from 'jspdf'

interface DashboardStats {
  totalUsers: number
  activeNow: number
  totalRevenue: number
  monthlyGrowth: number
}

interface ExportToPdfOptions {
  stats: DashboardStats
  dateRange: string
  title?: string
}

/**
 * Export dashboard stats to PDF report
 *
 * Uses jsPDF for lightweight PDF generation.
 * Creates a simple branded report suitable for management review.
 */
export const exportToPdf = ({
  stats,
  dateRange,
  title = 'ProAdmin Dashboard Report',
}: ExportToPdfOptions): void => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(title, pageWidth / 2, 25, { align: 'center' })

  // Metadata
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100)
  doc.text(`Date Range: ${formatDateRange(dateRange)}`, pageWidth / 2, 35, { align: 'center' })
  doc.text(`Generated: ${new Date().toLocaleString('de-DE')}`, pageWidth / 2, 42, {
    align: 'center',
  })

  // Divider
  doc.setDrawColor(200)
  doc.line(20, 50, pageWidth - 20, 50)

  // Stats section
  doc.setTextColor(0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Statistics Overview', 20, 65)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')

  const statsData = [
    ['Total Users', stats.totalUsers.toLocaleString('de-DE')],
    ['Active Now', stats.activeNow.toLocaleString('de-DE')],
    ['Total Revenue', formatCurrency(stats.totalRevenue)],
    ['Monthly Growth', `${stats.monthlyGrowth > 0 ? '+' : ''}${stats.monthlyGrowth}%`],
  ]

  let yPosition = 80
  statsData.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal')
    doc.text(label, 25, yPosition)
    doc.setFont('helvetica', 'bold')
    doc.text(value, 100, yPosition)
    yPosition += 12
  })

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text('Generated by ProAdmin Dashboard', pageWidth / 2, 280, { align: 'center' })

  // Save
  doc.save(`dashboard-report-${dateRange}.pdf`)
}

// Helpers
function formatDateRange(range: string): string {
  const labels: Record<string, string> = {
    '24h': 'Last 24 Hours',
    '7d': 'Last 7 Days',
    '30d': 'Last 30 Days',
  }
  return labels[range] || range
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('de-DE', {
    style: 'currency',
    currency: 'EUR',
  }).format(value)
}
